<?php 
require_once("Db.php");
require_once("LandAcquisition.php");
require_once("Client.php");
require_once("LandAcquisitionCategory.php");
require_once("landAcquisitionCategoryUnit.php");
require_once("AccessLevel.php");
require_once("Position.php");
require_once("ExpenseTypes.php");
require_once("TreeCropTypes.php");
require_once("CropDescription.php");
require_once("TreeCropTypesDescription.php");
require_once("PropertyDescription.php");
require_once("PropertyTypes.php");
require_once("Districts.php");
require_once("PropertyTypeDescription.php");
require_once("DistrictCropRate.php");
require_once("DistrictPropertyRate.php");
require_once("ProjectCoverage.php");
require_once("ProjectAffectedPerson.php");
require_once("PAP_CropTree.php");
require_once("PAP_Improvement.php");
require_once("Staff.php");
?>